# Generated by Django 5.1.3 on 2024-12-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='incident',
            name='responsible',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='team',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='type',
            field=models.CharField(choices=[('issue', 'Проблема'), ('request', 'Запрос'), ('incident', 'Инцидент')], default='issue', max_length=20),
        ),
    ]
