# Generated by Django 5.1.3 on 2024-12-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0002_remove_incident_updated_at_incident_responsible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
