# Generated by Django 5.1.3 on 2024-12-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('employee', 'Сотрудник'), ('support', 'Техподдержка'), ('admin', 'Администратор')], default='employee', max_length=12),
        ),
    ]
