# Generated by Django 5.1.3 on 2024-12-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Активная'), ('inactive', 'Неактивная')], default='active', max_length=10)),
                ('dependencies', models.ManyToManyField(blank=True, to='service.service')),
            ],
        ),
    ]
