# Generated by Django 5.1.3 on 2024-12-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Активная'), ('inactive', 'Неактивная')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('configuration_items', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Активная'), ('inactive', 'Неактивная')], default='active', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
